%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/thomas/Documents/ASCEND/datafiles/recordedData.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/11/17 14:59:45

%% Initialize variables.
filename = '/home/thomas/Documents/ASCEND/datafiles/recordedData.csv';
delimiter = ',';
startRow = 2;

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Time = dataArray{:, 1};
Altitude = dataArray{:, 2};
Temperature = dataArray{:, 3};
Pressure = dataArray{:, 4};
Latitude = dataArray{:, 5};
Longitude = dataArray{:, 6};
BatteryVoltage = dataArray{:, 7};


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;

%% Plot Data

plot(Time./3600, Temperature);

xlim([0 3.5708])
title("Temperature Data for ASCEND Flight 1");
ylabel("Temperature (\circC)");
xlabel("Time (Hours)");
