# CMake generated Testfile for 
# Source directory: /home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys
# Build directory: /home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(kwsys.testEncode "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/cmsysTestsC" "testEncode")
set_tests_properties(kwsys.testEncode PROPERTIES  _BACKTRACE_TRIPLES "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;1079;ADD_TEST;/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;0;")
add_test(kwsys.testTerminal "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/cmsysTestsC" "testTerminal")
set_tests_properties(kwsys.testTerminal PROPERTIES  _BACKTRACE_TRIPLES "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;1079;ADD_TEST;/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;0;")
add_test(kwsys.testConfigure "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/cmsysTestsCxx" "testConfigure")
set_tests_properties(kwsys.testConfigure PROPERTIES  _BACKTRACE_TRIPLES "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;1189;ADD_TEST;/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;0;")
add_test(kwsys.testSystemTools "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/cmsysTestsCxx" "testSystemTools")
set_tests_properties(kwsys.testSystemTools PROPERTIES  _BACKTRACE_TRIPLES "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;1189;ADD_TEST;/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;0;")
add_test(kwsys.testCommandLineArguments "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/cmsysTestsCxx" "testCommandLineArguments" "--another-bool-variable" "--long3=opt" "--set-bool-arg1" "-SSS" "ken" "brad" "bill" "andy" "--some-bool-variable=true" "--some-double-variable12.5" "--some-int-variable" "14" "--some-string-variable=test string with space" "--some-multi-argument" "5" "1" "8" "3" "7" "1" "3" "9" "7" "1" "-N" "12.5" "-SS=andy" "-N" "1.31" "-N" "22" "-SS=bill" "-BBtrue" "-SS=brad" "-BBtrue" "-BBfalse" "-SS=ken" "-A" "-C=test" "--long2" "hello")
set_tests_properties(kwsys.testCommandLineArguments PROPERTIES  _BACKTRACE_TRIPLES "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;1189;ADD_TEST;/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;0;")
add_test(kwsys.testCommandLineArguments1 "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/cmsysTestsCxx" "testCommandLineArguments1" "--ignored" "-n" "24" "--second-ignored" "-m=test value" "third-ignored" "-p" "some" "junk" "at" "the" "end")
set_tests_properties(kwsys.testCommandLineArguments1 PROPERTIES  _BACKTRACE_TRIPLES "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;1189;ADD_TEST;/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;0;")
add_test(kwsys.testDirectory "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/cmsysTestsCxx" "testDirectory")
set_tests_properties(kwsys.testDirectory PROPERTIES  _BACKTRACE_TRIPLES "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;1189;ADD_TEST;/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;0;")
add_test(kwsys.testEncoding "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/cmsysTestsCxx" "testEncoding")
set_tests_properties(kwsys.testEncoding PROPERTIES  _BACKTRACE_TRIPLES "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;1189;ADD_TEST;/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;0;")
add_test(kwsys.testFStream "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/cmsysTestsCxx" "testFStream")
set_tests_properties(kwsys.testFStream PROPERTIES  _BACKTRACE_TRIPLES "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;1189;ADD_TEST;/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;0;")
add_test(kwsys.testConsoleBuf "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/cmsysTestsCxx" "testConsoleBuf")
set_tests_properties(kwsys.testConsoleBuf PROPERTIES  _BACKTRACE_TRIPLES "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;1189;ADD_TEST;/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;0;")
add_test(kwsys.testSystemInformation "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/cmsysTestsCxx" "testSystemInformation")
set_tests_properties(kwsys.testSystemInformation PROPERTIES  _BACKTRACE_TRIPLES "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;1189;ADD_TEST;/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;0;")
add_test(kwsys.testDynamicLoader "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/cmsysTestsCxx" "testDynamicLoader")
set_tests_properties(kwsys.testDynamicLoader PROPERTIES  _BACKTRACE_TRIPLES "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;1189;ADD_TEST;/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;0;")
add_test(kwsys.testProcess-1 "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/cmsysTestProcess" "1")
set_tests_properties(kwsys.testProcess-1 PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;1201;ADD_TEST;/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;0;")
add_test(kwsys.testProcess-2 "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/cmsysTestProcess" "2")
set_tests_properties(kwsys.testProcess-2 PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;1201;ADD_TEST;/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;0;")
add_test(kwsys.testProcess-3 "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/cmsysTestProcess" "3")
set_tests_properties(kwsys.testProcess-3 PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;1201;ADD_TEST;/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;0;")
add_test(kwsys.testProcess-4 "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/cmsysTestProcess" "4")
set_tests_properties(kwsys.testProcess-4 PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;1201;ADD_TEST;/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;0;")
add_test(kwsys.testProcess-5 "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/cmsysTestProcess" "5")
set_tests_properties(kwsys.testProcess-5 PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;1201;ADD_TEST;/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;0;")
add_test(kwsys.testProcess-6 "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/cmsysTestProcess" "6")
set_tests_properties(kwsys.testProcess-6 PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;1201;ADD_TEST;/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;0;")
add_test(kwsys.testProcess-7 "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/cmsysTestProcess" "7")
set_tests_properties(kwsys.testProcess-7 PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;1201;ADD_TEST;/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;0;")
add_test(kwsys.testProcess-9 "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/cmsysTestProcess" "9")
set_tests_properties(kwsys.testProcess-9 PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;1201;ADD_TEST;/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;0;")
add_test(kwsys.testProcess-10 "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/cmsysTestProcess" "10")
set_tests_properties(kwsys.testProcess-10 PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;1201;ADD_TEST;/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;0;")
add_test(kwsys.testSharedForward "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/cmsysTestSharedForward" "1")
set_tests_properties(kwsys.testSharedForward PROPERTIES  _BACKTRACE_TRIPLES "/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;1234;ADD_TEST;/home/udooer/Downloads/cmake-3.14.0-rc3/Source/kwsys/CMakeLists.txt;0;")
